import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Alle cursussen',
      link: {
        type: 'generated-index',
        title: 'Alle Documentatie',
        slug: '/general',
        keywords: ['alle', 'documentatie', 'cursussen'],
      },
      items: [
        // Referentie naar de web frameworks category
        {
          type: 'category',
          label: 'Web Frameworks',
          link: {
            type: 'generated-index',
            title: 'Web Frameworks',
            slug: '/web-frameworks',
            keywords: ['web', 'frameworks', 'course'],
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'web-frameworks',
            },
          ],
        },
        // Referentie naar de python category
        {
          type: 'category',
          label: 'Python',
          link: {
            type: 'generated-index',
            title: 'Python',
            slug: '/python',
            keywords: ['python', 'programming', 'course'],
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'python',
            },
          ],
        },
        // Referentie naar de ICT Architecture category
        {
            type: 'category',
            label: 'ICT Architecture',
            link: {
              type: 'generated-index',
              title: 'ICT Architecture',
              slug: '/ict-architecture',
              keywords: ['ict', 'architecture', 'course'],
            },
            items: [
              {
                type: 'autogenerated',
                dirName: 'ict-architecture',
              },
              
            ],
        },
        // Referentie naar de SDDC Theorie category
        {
            type: 'category',
            label: 'Software Defined Data Center (SDDC)',
            link: {
                type: 'generated-index',
                title: 'Software Defined Data Center (SDDC)',
                slug: '/sddc',
                keywords: ['sddc', 'software defined data center', 'course'],
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'software-defined-data-center',
                },
            ],
        },
      ],
    }
  ]
};

export default sidebars;